AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: web-template

Parameters:
  NodeEnv:
    Type: String
  Project:
    Type: String

Resources:
  VPC:
    Type: AWS::Serverless::Application
    Properties:
      Location: './stacks/vpc.yml'
      Parameters:
        Project: !Ref Project
        NodeEnv: !Ref NodeEnv

  S3Storage:
    Type: AWS::Serverless::Application
    Properties:
      Location: './stacks/storage.yml'
      Parameters:
        Project: !Ref Project
        NodeEnv: !Ref NodeEnv

  WebServer:
    Type: AWS::Serverless::Application
    DependsOn:
      - S3Storage
      - VPC
    Properties:
      Location: './stacks/web-server.yml'
      Parameters:
        Project: !Ref Project
        NodeEnv: !Ref NodeEnv

  MongoDBServer:
    Type: AWS::Serverless::Application
    DependsOn:
      - WebServer 
      - VPC
    Properties:
      Location: './stacks/database-server.yml'
      Parameters:
        Project: !Ref Project
        NodeEnv: !Ref NodeEnv

  OwncastServer:
    Type: AWS::Serverless::Application
    DependsOn:
      - WebServer
      - VPC
    Properties:
      Location: './stacks/owncast-server.yml'
      Parameters:
        Project: !Ref Project
        NodeEnv: !Ref NodeEnv


